name = "HydraulicModels"
uuid = "7264e536-1170-4799-81c8-3c42137f862b"
authors = ["Stone Preston <stonepreston@protonmail.com> and contributors"]
version = "0.1.0"

[deps]
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[targets]
test = ["Test", "SafeTestsets"]
